# Generated by Django 5.1.1 on 2024-11-11 18:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('matricule', models.CharField(blank=True, max_length=10, unique=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Matières',
            },
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.personne')),
                ('matieres', models.ManyToManyField(blank=True, to='notes.matiere', verbose_name="Matières suivies par l'élève selon son niveau")),
            ],
            options={
                'verbose_name_plural': 'Elèves',
            },
            bases=('notes.personne',),
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='notes.personne')),
            ],
            bases=('notes.personne',),
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=10, null=True, unique=True)),
                ('matiere', models.ManyToManyField(to='notes.matiere')),
            ],
            options={
                'verbose_name_plural': 'Niveaux',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valeur', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.matiere')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.eleve')),
            ],
        ),
        migrations.AddField(
            model_name='eleve',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.niveau'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.enseignant'),
        ),
    ]
